### ISSUE TITLE
[BUG] onCreate -> items not properly reactive

### ISSUE THREAD

**Issue by Prinzhorn** [pstanoev/simple-svelte-autocomplete#102]
https://svelte.dev/repl/8ca8626f955640398fd0fe6cf3ad5dd5?version=3.42.3

```svelte
<script>
  import AutoComplete from "simple-svelte-autocomplete";

  const colors = ["White", "Red", "Yellow", "Green", "Blue", "Black"];
  let selectedColor;
	
  function handleCreate(newColor) {
    colors.push(newColor);
    colors = colors;
  }
</script>

<AutoComplete items={colors} bind:selectedItem={selectedColor} create onCreate={handleCreate} />
Selected color: {selectedColor}
```

1. Insert a color that doesn't exist, e.g. "Orange"
2. Hit Enter to add it
3. Observe that "Orange" is not selected (`Selected color: undefined`) and the UI still shows "Not found, add anyway?"
4. Typing will update the state, e.g. deleting a character "Orang"

Expected 3.: "Orange" is now selected and shows in the dropdown

In the video after typing "Orange" I hit enter. All it does is close the dropdown.

https://user-images.githubusercontent.com/679144/131128253-cbc63919-861d-4e64-9c00-7a8fe3d193b6.mp4

**Comment by pstanoev** [comment]
Hi @Prinzhorn thanks for reporting this, I will fix it.

**Comment by pstanoev** [comment]
Should be fixed with 2.2.1.

**Comment by Prinzhorn** [comment]
Thanks! The REPL doesn't appear to be fixed https://svelte.dev/repl/8ca8626f955640398fd0fe6cf3ad5dd5?version=3.42.3. The only change I see is that hitting ENTER doesn't close the dropdown anylonger. But it still doesn't update the UI and is in this state

![Selection_965](https://user-images.githubusercontent.com/679144/131461623-2cd1cc0b-02f2-4212-a4fb-339b5a6c5e9a.png)

**Comment by pstanoev** [comment]
The created item must be returned from the onCreate function.
https://svelte.dev/repl/3a54b05449b74c48ae078c42cab4527b?version=3.42.3

**Comment by Prinzhorn** [comment]
Thanks!

**Comment by v1ack** [comment]
Hello
I faced the same issue on v2.2.3 with using stores
here is a repl https://svelte.dev/repl/20dc7daa9dee4cea8ca66f366694a16f?version=3.42.3
![zZbopQBW7a](https://user-images.githubusercontent.com/11501957/133298118-f864d9af-774c-49dc-848b-e90710a33ba3.gif)
